POST http://localhost:4300/api/whook
Content-Type: application/json

{
    "my_key": {
      "foo": "bar",
      "hello": null
    },
    "other": -69.007,
    "again": 39.5403,
    "sample": "value"
}

###
GET http://localhost:4300/api/whook?foo=bar&hello=ciao

###
GET http://localhost:4300/api/whook

###
POST http://localhost:4300/api/whook?a=b
Content-Type: application/json?foo=bar

{
 "a": 1
}