POST http://localhost:4300/api/whook?pippo=4&foo=bar
Content-Type: application/json

{
    "my_key": {
      "foo": "bar",
      "hello": null
    },
    "other": -69.007,
    "again": 39.5403,
    "sample": "value"
}

###
GET http://localhost:4300/api/whook?foo=bar&hello=ciao

###
GET http://localhost:4300/api/whook

###
POST http://localhost:4300/api/whook

###
POST http://localhost:4300/api/whook?foo=bar&pippo=1&pluto=caio


###
POST http://localhost:4300/api/whook?foo=bar&pippo=1&pluto=caio
Content-Type: application/x-www-form-urlencoded

ciao=helo&pippo=1

###
POST http://localhost:4300/api/whook
###
POST http://localhost:4300/api/whook?foo=bar&pippo=1&pluto=caio
Content-Type: application/x-www-form-urlencoded

ciao=helo&pippo=1
